### ISSUE TITLE
Engauge6 crashes when exporting several curves as CSV files in Windows 10 (64)

### ISSUE THREAD

**Issue by alFassi** [markummitchell/engauge6#63] opened 2016-02-21 10:14 UTC
First I would like to thank you all for your commitment with  ENGAUGE project.
I have installed  the last available version through the windows installer digit-exe-windows-32-bit-installer-6_2.msi, my OS being Windows 10 (64 bits). 
All, installation, Axes definition, curves scan and export, works fine when dealing with one curve at the time.
But, when I am trying to digitize different curves again scanning is fine,  I can even save .dig file except that ENGAUGE crashes during the export to CSV file :-((
I could proceed step-wise, 1 curve at  the time but it is a bit fastidious!
Do you have any way to solve or turnaround my issue?
All the best

**Comment by crayxt** [comment] 2016-02-21 10:19
Could you provide your .dig file?

**Comment by alFassi** [comment] 2016-02-21 10:54
Thank you for your quick feedback.
I made a new test and I was able to digitize up to 4 curves when Engauge crashes again.
So I am attaching the corresponding zipped 
[Model test result Q11 vs n11.zip](https://github.com/markummitchell/engauge6/files/139570/Model.test.result.Q11.vs.n11.zip)
.dig file
All the best

**Comment by crayxt** [comment] 2016-02-21 16:50
Ok, so I've built current Engauge master tree with MSVC 2013 and I don't see this issue. With the release 6.2 from Github I can confirm that export crashes Engauge 6.2. Very likely the issue will be gone in upcoming release - let @markummitchell confirm.

**Comment by markummitchell** [comment] 2016-02-21 20:18
I believe the fix for this issue was implemented on December 20, which unfortunately missed the November release date of version 6.2. However, version 7 should be coming out in the next week, or two at the latest. Version 7 can read old dig files from previous versions.

**Closed by markummitchell** 2016-02-21 20:18 UTC

**Comment by crayxt** [comment] 2016-02-24 03:44
@markummitchell by the way, why version 7, not 6.3?

**Comment by markummitchell** [comment] 2016-02-24 04:04
Support for the new 'advanced mode' breaks the version 6 file structure. Specifically, (1) a Document can have 3 or 4 axis points, and (2) a Document can have multiple coordinate systems (=multiple pairs of axes). I'm thinking that these are advanced features that would confuse or slow down beginning/intermediate users, so the new features only appear when an Image is imported in Advanced mode (File / Import Advanced). Also, to keep the code simple (it is now at 30,000 SLOCs), and keep the GUI simple, I decided that once a file is imported with 4 axis points or with multiple coordinate systems, the number of axis points and coordinate systems can never be changed (=no new Dialog boxes for changing the counts).

Since version 7 is a big change, I am adding a lot of new regression tests (even today) to make sure the new code works reliably.

Hopefully the version number change is not a problem with downstream. Also, the fact that I called the project engauge6 and the version number is 7 may be a problem. Don't know how to fix that.

**Comment by crayxt** [comment] 2016-02-24 04:10
@markummitchell Yeah, thanks, makes sense now - I forgot about multiple coordinate systems.

Regarding the name - If you rename this repository just to engauge, I think nothing will break? Linux distros has it as engauge-digiziter, so this part is good.
