### ISSUE TITLE
Feature query: Guide lines to help add axis points?

### ISSUE THREAD

**Issue by sebjameswml** [markummitchell/engauge6#44] opened 2015-12-07 16:33 UTC
I have a graph from a paper on which the origin of the axes is not marked. That is, the y axis is located at x = 32 (approx), but it's not marked. The first x axis tick is 100, then 200, 300 etc. 

Here's the graph in question*:

![bevan_wilson_fig_6b](https://cloud.githubusercontent.com/assets/130308/11632503/58630fac-9cff-11e5-8286-fd118009e104.png)

This gives me a problem when fixing the axis marks - I want to put the 3 axis points on the axes, and enter numbers for the coordinates of these three points. The points on the x axis are fine; for example I could choose 100,0 and 500,0. However, when I select a point on the y axis, I don't know what the x value is without getting my ruler and calculator out.

Now, If I could draw a vertical and horizontal line on the diagram - vertical at x=100 and horizontal at y=200, then I could place my third axis point where these two lines cross.

I couldn't find a feature like this, but I'd not be surprised if I missed something. What would you do to process this graph?

Cheers,

Seb James

* It's a firing rate vs. injection current graph for a neuron of the subthalamic nucleus in a rat

**Comment by wackywendell** [comment] 2015-12-07 18:54
I've run into this too.

Another way of dealing with this might be to simply not require each axis point to have both an x- and y- coordinate. For example, in this case, marking three points at (?, 280), (100, 0), and (600, 0) is enough information to define an axis, even if you don't assume they are at right angles. 

I've also had to deal with the case where *neither* axis has a well-labeled origin. In that case, one would want to be able to place 4 points: 2 on the x-axis with no y-coordinate specified, and 2 on the y-axis with no x-axis specified. 

Its a bit of a tricky problem!

**Comment by markummitchell** [comment] 2015-12-08 06:24
If three axis points with fully populated (X,Y) coordinates are defined then there are 6 values for 6 equations embedded in the matrix equation that transforms Screen coordinates to Graph coordinates
<pre>
(x0G   x1G   x2G)    (t00  t01 t02)  (x0S   x1S  x2S)
(y0G   y1G   y2G) = (t10  t11 t12)  (y0S   y1S  y2S)
(1        1        1     )    (t21  t21 t22)  (1       1       1     )
</pre>

I think some coordinate values can be skipped by reformulating the matrix equation as follows. Since the x coordinate of the third point is undefined, a fourth point is added to supply the 6th value.
<pre>
(x0G   x1G   ?       ?     )    (t00  t01 t02)  (x0S   x1S  x2S  x3S)
(y0G   y1G   y2G  y3G) = (t10  t11 t12)  (y0S   y1S  y2S  y3S)
(1        1        1       1     )    (t21  t21 t22)  (1       1       1       1    )
</pre>
In sebjamesxml's example, the two question mark values are the same (both vertical points are on the y axis), but in general we cannot assume any relationships between the unspecified values.

I think the approach is to use some scheme like Levenberg-Marquardt (levmar) and turn this into a multivariable optimization problem. Specifically, the 6 desired graph coordinate values are compared to the 6 computed graph coordinate values using the second equation above.  The root-mean-square of the error is computed, and supplied to the levmar library for solving for the transformation matrix terms.

This will take a little time to implement. Perhaps the big concern is that it adds dependencies to LAPACK and potentially BLAS.

**Comment by AlexanderTaeschner** [comment] 2016-02-01 11:53
In WebPlotDigitizer always 4 points are specified. Maybe one can use a similar algorithm here (source seems to be in https://github.com/ankitrohatgi/WebPlotDigitizer/blob/master/javascript/core/axes/xy.js).

**Comment by markummitchell** [comment] 2016-02-02 04:25
Thanks Alexander. The calculations are understood - the challenge is how to keep the user interface simple and still offer the feature. Also, I am currently working on issue #2 which is a major upgrade. After #2 is fixed, then this issue is next.

For this issue, I am currently thinking about offering either the normal set of 3 points with (x,y) coordinates, or offering 4 points with either an x or y coordinate for each point. 

Support for multiple coordinate systems (#2) and 4-axis-points  (this issue) are advanced, and likely to be used by only a few people. The new code has a new 'Import Advanced' option for these special features, with the existing 'Import' option for normal graphs. However, if there is a better approach I would like to hear it.

**Comment by markummitchell** [comment] 2016-02-13 21:38
Working, with its own regression test. Will be part of next release as version 7.

**Closed by markummitchell** 2016-02-13 21:38 UTC
Labels: enhancement
