### ISSUE TITLE
Support drag and drop of DIG files into Engauge main window

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#31] opened 2015-11-02 04:48 UTC
If I drag and drop DIG file into Engauge window, it says that it is unable to load an image from that file.
Is it possible to detect extension of incoming file, and treat .dig files accordingly, e.g. open them as Engauge dig files.
Thanks,

**Comment by crayxt** [comment] 2015-11-02 04:48
Platform is Windows 7 64-bit.

**Comment by markummitchell** [comment] 2015-11-05 17:54
Duplicate of issue #34

**Closed by markummitchell** 2015-11-05 17:54 UTC
